# Generated by Django 5.1.4 on 2024-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('hpnumber', models.IntegerField()),
                ('skills', models.ManyToManyField(related_name='profiles', to='skillsharingbackend.skills')),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='teachers',
            field=models.ManyToManyField(related_name='skills', to='skillsharingbackend.teachers'),
        ),
    ]
